insert into blogpost (author, content, date, title)
values('Toni Maijala', 'Curabitur ut nunc nec risus vulputate maximus id eu turpis. Vivamus facilisis iaculis imperdiet. Pellentesque at elementum diam. Nullam ultrices odio enim, sit amet venenatis nisl imperdiet nec. Duis sagittis rutrum posuere. Cras efficitur cursus tellus faucibus sollicitudin. Donec nec tellus at quam pulvinar sagittis. Nam elementum, risus placerat malesuada egestas, tellus orci viverra lectus, eu consequat lacus felis nec nisi. Integer in feugiat metus.

Vivamus porttitor eu leo ut laoreet. Pellentesque ac efficitur orci. Sed sodales vel magna a varius. Proin fermentum velit vel ligula consequat sollicitudin. Integer at pharetra urna. Fusce sit amet nisl luctus, ultrices leo ut, tincidunt diam. Ut accumsan ante volutpat ante suscipit finibus non vitae erat. Quisque et ornare enim.

Etiam id justo vel neque dignissim feugiat. Phasellus dignissim accumsan turpis. Etiam blandit tempor turpis, non eleifend lacus egestas et. Nam quis maximus quam. Curabitur sapien diam, blandit sed ligula sit amet, tempor ornare turpis. Sed nec tortor et purus consequat pellentesque. Aliquam eget tellus diam. Vivamus faucibus ex libero, vel auctor justo dictum sed. Vivamus mollis turpis sed turpis laoreet consectetur. Vivamus iaculis iaculis enim ac convallis. Praesent vel purus ut ligula congue consectetur. Suspendisse sollicitudin facilisis felis, at viverra ipsum venenatis in.','2019-03-14', 'Test title'),
      ('Toni Maijala', 'Aliquam consectetur tempus massa ac dignissim. Donec posuere est vel dui euismod cursus. Phasellus porttitor dolor ac risus tristique, eu bibendum lectus tincidunt. Quisque efficitur accumsan mauris, sit amet vestibulum eros convallis sed. Maecenas posuere fermentum justo quis viverra. Pellentesque vel augue elit. Ut placerat libero sed cursus mollis. Pellentesque mi mi, euismod a cursus eu, convallis elementum ex. Etiam malesuada turpis sapien, vitae dapibus odio dignissim et. Pellentesque accumsan nibh nibh, vehicula auctor elit feugiat egestas.

Nam ac pulvinar nisi. Sed at aliquet tortor, vel porta ex. Duis congue libero quis dolor hendrerit suscipit. Vestibulum tempus sem dolor, eu lacinia risus faucibus imperdiet. Pellentesque ultrices, elit eu scelerisque accumsan, leo est iaculis mauris, ut pellentesque lorem odio eget magna. Nullam laoreet a ex ac auctor. Fusce vestibulum ligula eget pretium facilisis.

Donec ipsum erat, pulvinar et imperdiet ac, mollis a nulla. Curabitur lacinia nisl sit amet ex eleifend, vel auctor tellus sagittis. Sed quis enim cursus, lacinia dolor vitae, consectetur lacus. Pellentesque eu arcu lobortis metus efficitur venenatis eget eget orci. Praesent efficitur cursus ultricies. Sed dui eros, egestas ut quam at, gravida tincidunt neque. Nunc semper leo sit amet neque facilisis viverra. In quam sem, mollis non metus iaculis, feugiat dictum sem. Suspendisse auctor tempor facilisis. In pharetra cursus enim quis congue. Vestibulum sed ultrices augue. Nulla ullamcorper justo ut tellus sagittis, nec porttitor lorem tincidunt. In facilisis blandit augue, nec aliquam justo rutrum at. Cras non dictum massa, quis rutrum enim. Sed porta dolor quis tincidunt gravida. Suspendisse potenti.

Morbi dictum felis eu congue semper. Nullam id dui eu est volutpat tincidunt id nec massa. Nullam nec velit tincidunt, convallis mi nec, viverra enim. Donec laoreet maximus tellus, tincidunt scelerisque leo venenatis ac. Etiam ut ullamcorper magna. Aliquam malesuada ipsum a lorem accumsan, vel efficitur mi viverra. Morbi quis erat in purus varius fringilla. Nullam facilisis nulla a libero posuere facilisis. Nullam at laoreet diam, tristique aliquet ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sed ornare eros, sit amet efficitur augue. Morbi hendrerit ligula sed cursus scelerisque. Nulla at rutrum nulla, at mattis erat.

Fusce placerat massa tellus, quis egestas diam accumsan in. Vestibulum rhoncus magna et erat posuere, sed faucibus metus faucibus. Sed nec nisl nec velit ornare sollicitudin in et felis. Nulla facilisi. Quisque commodo leo mattis tellus consequat, in aliquam tellus hendrerit. Nullam aliquet ornare lacus eget euismod. Ut pulvinar, nunc eget elementum congue, dui augue suscipit lectus, id lobortis est erat a felis. Cras sapien ligula, molestie a ultricies nec, mattis vitae felis.

Cras ut libero id tortor lacinia varius ut non augue. Donec porttitor sed neque et blandit. Pellentesque sit amet vehicula dui, vitae commodo massa. Maecenas sed nunc mi. Aliquam non egestas tortor. Vivamus iaculis lacus enim, a tristique quam ornare id. Ut nunc nibh, mollis ut eros eget, finibus gravida libero. Donec neque enim, lacinia vel interdum vel, euismod quis leo. Pellentesque efficitur erat id ante dapibus lobortis. Quisque et libero id dolor blandit vehicula. Proin lobortis placerat purus, nec aliquet magna convallis fringilla. Cras lorem felis, maximus ut ligula eget, rutrum porta justo.','2019-03-16', 'Veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery llllooooooooooooooooonnnnggggggggggggg tttttttiiiiiiiiiiiiiitttllllllllllleeeeeeeeeeeeeeeee'),
      ('Toni Maijala', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et massa auctor, lacinia nunc vitae, pharetra ex. Vestibulum quis hendrerit enim. Sed mollis mauris a venenatis pretium. Quisque varius sed dui at volutpat. Morbi enim nisi, iaculis vitae semper eget, accumsan eu lacus. Quisque eu ante nec ante scelerisque aliquet in quis enim. Donec egestas eros ut velit euismod ultricies. Morbi convallis faucibus cursus. Ut ac lorem eget tortor placerat volutpat eget id risus. Duis volutpat nisl eu neque dignissim, id scelerisque ipsum suscipit. Aenean quis massa sit amet est elementum suscipit. In at lobortis ligula. Nunc convallis est nibh, non consectetur sem volutpat eget. Praesent luctus diam ipsum.

Curabitur efficitur non purus ut venenatis. Sed erat ipsum, laoreet at mollis in, pretium a turpis. Morbi vestibulum turpis nec orci vehicula, eu cursus ex scelerisque. Vivamus ut pellentesque est, vel lacinia dolor. Quisque ultrices, sem sit amet mollis placerat, sapien est maximus arcu, quis suscipit tortor magna nec erat. Cras a tortor vestibulum, ultricies nunc eu, maximus odio. Morbi vel purus eget orci sollicitudin sagittis sed vel dui. Curabitur congue vitae leo ac ultrices. Vivamus eget felis a leo vehicula interdum vitae vel ligula. Nullam ac elementum leo. Proin convallis odio justo, et sagittis ligula pulvinar vel. Sed mattis id urna nec bibendum. Proin ante nunc, laoreet id viverra a, mollis in metus. Sed ac tristique elit. Vestibulum massa urna, ullamcorper nec egestas eu, viverra eget velit. Vivamus sed diam sed purus feugiat ornare.

Donec convallis leo mattis, lobortis diam vitae, laoreet nisi. Vestibulum venenatis nunc ut metus commodo porta. Nulla imperdiet auctor sollicitudin. Phasellus eleifend neque nec tincidunt sodales. Aliquam sodales sollicitudin mattis. In eget finibus orci, quis lobortis nulla. Maecenas laoreet blandit felis in viverra. Maecenas ut urna ultrices, posuere odio non, sollicitudin dolor. Sed consequat, turpis vestibulum facilisis convallis, libero turpis pharetra elit, sed aliquet ex dui sed ligula. In hac habitasse platea dictumst. Proin non dui lorem.

Nullam lobortis quam velit, et euismod quam vestibulum in. Proin semper faucibus neque, nec sagittis ipsum. Morbi vitae risus lacinia, pretium risus vel, accumsan tellus. Nullam lectus nulla, mollis a tincidunt ut, aliquet non urna. Vivamus vitae lorem metus. Suspendisse a imperdiet tellus, in suscipit mauris. Phasellus ultrices pellentesque nisi id aliquam. Quisque rutrum varius ex. Quisque ultrices, lacus non euismod malesuada, leo diam imperdiet ex, sed accumsan magna justo sit amet ligula. Donec maximus risus sed neque pellentesque euismod. Nunc convallis nibh urna, eget molestie turpis fermentum eget. Donec tempor sagittis luctus. Nulla auctor metus sodales eros malesuada, vitae faucibus velit blandit. Praesent lectus tellus, ornare sit amet justo eget, finibus volutpat neque.

In hac habitasse platea dictumst. Cras luctus eros quis auctor cursus. Fusce maximus nibh nec orci mollis condimentum. Donec sed accumsan lorem. Vestibulum vehicula lobortis tellus ac varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In velit risus, vestibulum vel justo eu, condimentum facilisis ipsum. Nullam hendrerit nibh nec magna congue ullamcorper. Nulla volutpat sapien at sapien posuere tempus. Morbi vitae odio ut lacus posuere viverra ut vel odio. Aenean interdum et arcu in cursus. Cras sollicitudin mattis finibus. Nulla tincidunt porttitor sem a tempor. Sed porttitor arcu at sagittis viverra.','2019-03-16', 'Title 3');

insert into tag (tagname)
values ('ps4'),
       ('xbox'),
       ('game console'),
       ('pc');

insert into post_tags
values (1,1),
       (1,3);